# Generated by Django 5.0.9 on 2024-09-23 00:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('slider', 0)], blank=True, block_lookup={0: ('home.blocks.CarouselBlock', (), {})}),
        ),
    ]
