# Generated by Django 5.0.9 on 2024-09-24 23:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('slider', 0), ('top_feature', 1)], blank=True, block_lookup={0: ('home.blocks.CarouselBlock', (), {}), 1: ('home.blocks.TopFeatureBlock', (), {})}),
        ),
    ]
