# Generated by Django 5.0.9 on 2024-09-25 00:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('slider', 0), ('top_feature', 1), ('about', 10)], blank=True, block_lookup={0: ('home.blocks.CarouselBlock', (), {}), 1: ('home.blocks.TopFeatureBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.TextBlock', (), {'required': False}), 6: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'exemple: fa fa-award fa-3x', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('icon', 7), ('title', 3), ('description', 5)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 2), ('title', 3), ('title_caption', 4), ('subtitle', 3), ('description', 5), ('cta_txt', 3), ('cta_url', 6), ('icon_cards', 9)]], {})}),
        ),
    ]
