# Generated by Django 5.0.9 on 2024-09-22 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topbar', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('icon', models.CharField(blank=True, help_text='"exemple: fab fa-twitter"', max_length=255)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.navigationsettings')),
                ('sc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.socialnetwork')),
            ],
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='socials',
            field=models.ManyToManyField(through='base.SiteSocialNetwork', to='base.socialnetwork', verbose_name='Réseaux sociaux'),
        ),
    ]
