# Generated by Django 5.0.9 on 2024-09-29 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_servicepage_icon_servicepage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepage',
            old_name='image',
            new_name='service_icon',
        ),
        migrations.RenameField(
            model_name='servicepage',
            old_name='service_banner_image',
            new_name='service_image',
        ),
    ]
