# Generated by Django 5.0.9 on 2024-10-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_aboutpage_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='team_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
