# Generated by Django 5.0.9 on 2024-10-05 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_menu_navigationsettings_ft_one_adress_and_more'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='ft_two_title',
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='ft_one_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.menu'),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
