# Generated by Django 5.0.9 on 2024-10-05 16:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_navigationsettings_ft_two_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='ft_one_menu',
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='ft_four_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='ft_four_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='ft_three_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.menu'),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='ft_two_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.menu'),
        ),
    ]
