# Generated by Django 5.0.9 on 2024-10-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_contactpage_send_btn_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='other_service_header',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
