# Generated by Django 5.0.9 on 2024-10-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_blogtagindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='other_blog_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tag_section_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
