# Generated by Django 5.0.9 on 2024-10-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_jobhomepage_jobpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhomepage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
