# Generated by Django 5.0.9 on 2024-10-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_jobhomepage_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='service_icon',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
