# Generated by Django 5.0.9 on 2024-10-19 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_servicepage_service_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicehomepage',
            name='banner',
        ),
    ]
